### ISSUE TITLE
Speed up data delivery

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#133] opened 2021-06-22 13:50 UTC
Not sure why, but currently it can take minutes to deliver small amount of data (less than 100 lines).

![image](https://user-images.githubusercontent.com/136346/122936557-88833f00-d371-11eb-8527-5f7603ae016c.png)

**Comment by areedv** [comment] 2021-07-05 10:34
If delivery contains dg full aggregation is performed for the current registry due to the selected scheme where a dg is valid from its year and onward. I suspect this issue to be a feature (of our own design) and not a bug or other shortcoming. I will close this issue, but please reopen if this behavior is unacceptable. If so, please also provide information on the data (used for upload) that caused the delay

**Comment by arnfinn** [comment] 2022-08-18 12:13
Updating delivery timings tar ekstremt lang tid, så jeg gjenåpner denne.

**Comment by arnfinn** [comment] 2023-01-09 15:02
Kjører litt tidstesting. Følgende linje bruker over et minutt:
```
  aggs <- get_indicator_level(aggs, ind)
```

**Comment by arnfinn** [comment] 2023-01-09 15:10
Dette betyr at mye av tregheten vil forsvinne hvis https://github.com/mong/mongts/issues/520 ordnes.

**Closed** 2023-01-26 14:49 UTC
